name: Reusable workflow to run actions

on:
  workflow_call:
    inputs:
      network:
        description: 'Network to use'
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Print network
        run: |
          echo "Network: ${{ inputs.network }}"
